algoritmo "semnome"
// Função :
// Autor :
// Data : 21/08/2023
// Seção de Declarações 
var

   valor : real
   taxa : inteiro

inicio

      escreval ("Calculando Desconto")
      escreval()
      
      escreval ("Informe o valor do produto...: ")
      escreval ()
      leia (valor)
      
      escreval ("Informe o desconto...: ")
      escreval ()
      leia (taxa)
      
      escreval ("Você irá pagar R$", (valor - ((valor * taxa)/ 100)))

fimalgoritmo
